# Site settings
title: Saurabh Majumdar
description: 'One person's thoughts'
url: 'http://www.smajumdar.com' 
baseurl: '/'
 google_analytics: 'UA-73101412-1'

author:
  name: 'Saurabh Majumdar'
  email: mail@smajumdar.com
  twitter_username:
  github_username:
  linkedin_username:

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']